### ISSUE TITLE
Feature Request: Paladin Tanks

### ISSUE THREAD

**Issue by ghost** [MarcelineVQ/Tankalyze#1]
No more judgement taunt!  Paladins have a proper taunt now so I'd hope you update your awesome addon to take this into account and perhaps even put in some stuff for Shaman tanks as well.

Personally I'd also love to see a way to output to SAY/PARTY/RAID chat if anyone who is NOT a tank in group uses certain high-threat or taunt abilities such as hunter pet 'growl' or warlock 'hellfire' or similar.  That way we can identify it and the group doesn't blame the tank for 'losing threat'.

In an ideal world it shouldn't be necessary but we are dealing with the instrumental-play meta nonsense of those who played with that terrible WoW Classic community and so on.  Playerbase has expectations of tanks and either tanks find a good group or they get abused (alongside abuse against healers) which leads to a lot of issues.

**Comment by MarcelineVQ** [comment]
Added paladin taunt and enabled addon for paladin class
