### ISSUE TITLE
Feature Request: Shaman Tank Taunt Resist

### ISSUE THREAD

**Issue by OonaFae** [MarcelineVQ/Tankalyze#2]
I understand they're still a meme so if you don't think it's worth the effort I understand.
Shaman Tank Taunt - Earthshaker Slam

If you need any additional information I'll do my best to provide.

-Cheers!

**Comment by AyrianaWoW** [comment]
Quoting from my (now completed) Paladin Tank request:

> Personally I'd also love to see a way to output to SAY/PARTY/RAID chat if anyone who is NOT a tank in group uses certain high-threat or taunt abilities such as hunter pet 'growl' or warlock 'hellfire' or similar. That way we can identify it and the group doesn't blame the tank for 'losing threat'.

I'd like this added for all tanks. If any person is not designated as a 'tank' and is using certain high-threat abilities or taunts (mostly hunters who forget to disable taunts on pets) then it should output a message in chat (say, party/raid, whisper, whatever channel we should be able to choose) and this way we can both help players with their mistakes and mitigate potential toxicity towards newly-minted tanks of all the tankable-classes, be they Warrior, Druid, Paladin, or Shaman.
