### ISSUE TITLE
Feature Request: Threat Tracking of Non-Tank High-Threat Taunts/Abilities

### ISSUE THREAD

**Issue by ghost** [MarcelineVQ/Tankalyze#3]
Quoting from a previous issue:

> Personally I'd also love to see a way to output to SAY/PARTY/RAID chat if anyone who is NOT a tank in group uses certain high-threat or taunt abilities such as hunter pet 'growl' or warlock 'hellfire' or similar. That way we can identify it and the group doesn't blame the tank for 'losing threat'.

So yeah I'd still like to see this be a thing.  You already track tank abilities so just add some stuff for non-tank abilities (both direct taunts used on a tank's target by anyone who isn't the tank AND high-threat abilities such as Warlock Hellfire, basically any usable class ability that draws an abnormally-high amount of threat and/or says that it causes high threat in the tooltip).

**Comment by MarcelineVQ** [comment]
For me that's not in the scope of what this addon is for: which is to inform the raid about what the tank is doing not the other way around.
